// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// updateZcpp
void updateZcpp(SEXP ZSEXP, SEXP YSEXP, SEXP BSEXP, SEXP B2SEXP, const arma::vec& bk2_all, SEXP YBtSEXP, SEXP QSEXP, SEXP ZmultiplierSEXP, double L1, double multiplier, int inner_iter, int iter, bool Y_is_fbm, int n, int p);
RcppExport SEXP _PLIER2_updateZcpp(SEXP ZSEXPSEXP, SEXP YSEXPSEXP, SEXP BSEXPSEXP, SEXP B2SEXPSEXP, SEXP bk2_allSEXP, SEXP YBtSEXPSEXP, SEXP QSEXPSEXP, SEXP ZmultiplierSEXPSEXP, SEXP L1SEXP, SEXP multiplierSEXP, SEXP inner_iterSEXP, SEXP iterSEXP, SEXP Y_is_fbmSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ZSEXP(ZSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type YSEXP(YSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type BSEXP(BSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type B2SEXP(B2SEXPSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bk2_all(bk2_allSEXP);
    Rcpp::traits::input_parameter< SEXP >::type YBtSEXP(YBtSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type QSEXP(QSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ZmultiplierSEXP(ZmultiplierSEXPSEXP);
    Rcpp::traits::input_parameter< double >::type L1(L1SEXP);
    Rcpp::traits::input_parameter< double >::type multiplier(multiplierSEXP);
    Rcpp::traits::input_parameter< int >::type inner_iter(inner_iterSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< bool >::type Y_is_fbm(Y_is_fbmSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    updateZcpp(ZSEXP, YSEXP, BSEXP, B2SEXP, bk2_all, YBtSEXP, QSEXP, ZmultiplierSEXP, L1, multiplier, inner_iter, iter, Y_is_fbm, n, p);
    return R_NilValue;
END_RCPP
}
// updateZcppOld
void updateZcppOld(arma::mat& Z, const arma::mat& Y, const arma::mat& B, const arma::mat& B2, const arma::vec& bk2_all, const arma::mat& YBt, arma::mat& Q, const arma::mat& Zmultiplier, double L1, double multiplier, int inner_iter, int iter);
RcppExport SEXP _PLIER2_updateZcppOld(SEXP ZSEXP, SEXP YSEXP, SEXP BSEXP, SEXP B2SEXP, SEXP bk2_allSEXP, SEXP YBtSEXP, SEXP QSEXP, SEXP ZmultiplierSEXP, SEXP L1SEXP, SEXP multiplierSEXP, SEXP inner_iterSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B2(B2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bk2_all(bk2_allSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type YBt(YBtSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Zmultiplier(ZmultiplierSEXP);
    Rcpp::traits::input_parameter< double >::type L1(L1SEXP);
    Rcpp::traits::input_parameter< double >::type multiplier(multiplierSEXP);
    Rcpp::traits::input_parameter< int >::type inner_iter(inner_iterSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    updateZcppOld(Z, Y, B, B2, bk2_all, YBt, Q, Zmultiplier, L1, multiplier, inner_iter, iter);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PLIER2_updateZcpp", (DL_FUNC) &_PLIER2_updateZcpp, 15},
    {"_PLIER2_updateZcppOld", (DL_FUNC) &_PLIER2_updateZcppOld, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_PLIER2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
